/**
 * Spike 4: drive the real idle mode in a real pty and capture the evidence.
 *
 * `script(1)` gives the child a controlling terminal; this driver waits for the
 * app's `READY` marker, then sends keystrokes through the pty the way a
 * keyboard would, and checks what came back. The point is to prove the things a
 * fake terminal cannot: that the TUI actually paints on a tty, that real Enter
 * submits, that Ctrl+C twice exits, and that the terminal is left cooked with the
 * cursor visible.
 *
 * Evidence goes to `spikes/out/4-idle-pty.txt` (override with LOOP_SPIKE_OUT).
 *
 * Run: `npm run spike:idle`
 */

import { spawn } from "node:child_process";
import {
  mkdirSync,
  readFileSync,
  mkdtempSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const appPath = join(here, "4-idle-app.ts");
const tsxCli = join(here, "..", "node_modules", "tsx", "dist", "cli.mjs");
const outPath = process.env.LOOP_SPIKE_OUT ?? join(here, "out", "4-idle-pty.txt");

const CASES: {
  name: string;
  keys: Array<{ afterMs: number; data: string }>;
}[] = [
  {
    // A typed sentence, submitted with a real Enter.
    name: "submit",
    keys: [{ afterMs: 400, data: "split this into beads please\r" }],
  },
  {
    // Text on the line, then Ctrl+C twice inside the arm window.
    name: "ctrlc",
    keys: [
      { afterMs: 400, data: "half-typed thought" },
      { afterMs: 300, data: "\x03" },
      { afterMs: 150, data: "\x03" },
    ],
  },
];

/** POSIX shell single-quote escaping — the child command goes through `/bin/sh`. */
function shq(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

interface CaseResult {
  name: string;
  rc: number | null;
  outcome: string;
  rawModeAfter: boolean;
  cursorHiddenAfter: boolean;
  capture: string;
  timedOut: boolean;
}

function runCase(test: (typeof CASES)[number]): Promise<CaseResult> {
  const captureFile = join(
    mkdtempSync(join(tmpdir(), "loop-idle-pty-")),
    "capture.txt",
  );
  const childCommand = `${shq(process.execPath)} ${shq(tsxCli)} ${shq(
    appPath,
  )} ${shq(test.name)}`;

  return new Promise((resolve) => {
    const child = spawn(
      "script",
      ["-q", "-f", "-c", childCommand, captureFile],
      { stdio: ["pipe", "pipe", "pipe"] },
    );

    let live = "";
    let keysSent = false;
    const timers: ReturnType<typeof setTimeout>[] = [];

    const timeout = setTimeout(() => {
      child.kill("SIGKILL");
    }, 30_000);

    const finish = (timedOut: boolean): void => {
      clearTimeout(timeout);
      for (const timer of timers) clearTimeout(timer);
      let capture = "";
      try {
        capture = readFileSync(captureFile, "utf8");
      } catch {
        capture = live;
      }
      const outcomeLine = /OUTCOME (\{[^\n]*\})/u.exec(capture)?.[1] ?? "";
      const rawLine = /RAWMODE (yes|no)/u.exec(capture)?.[1] ?? "yes";
      // Anything that hid the cursor after the outcome must have shown it again.
      const outcomeIndex = capture.lastIndexOf("OUTCOME");
      const tail = outcomeIndex === -1 ? capture : capture.slice(outcomeIndex);
      const hides = (tail.match(/\x1b\[\?25l/gu) ?? []).length;
      const shows = (tail.match(/\x1b\[\?25h/gu) ?? []).length;
      resolve({
        name: test.name,
        rc: timedOut ? null : (child.exitCode ?? null),
        outcome: outcomeLine,
        rawModeAfter: rawLine === "yes",
        cursorHiddenAfter: hides > shows,
        capture,
        timedOut,
      });
    };

    child.stdout.setEncoding("utf8");
    child.stdout.on("data", (chunk: string) => {
      live += chunk;
      if (keysSent || !live.includes("READY")) return;
      keysSent = true;
      let delay = 200;
      for (const key of test.keys) {
        delay += key.afterMs;
        timers.push(setTimeout(() => child.stdin.write(key.data), delay));
      }
    });
    child.stderr.resume();
    child.on("error", () => finish(true));
    child.on("close", () => finish(false));
  });
}

function printable(text: string): string {
  return text
    .replace(/\x1b\[[0-9;?]*[a-zA-Z]/gu, "")
    .replace(/\x1b\][^\x07\x1b]*(\x07|\x1b\\)/gu, "")
    .replace(/\r\n/gu, "\n")
    .replace(/\r/gu, "\n");
}

const results: CaseResult[] = [];
for (const test of CASES) {
  // eslint-disable-next-line no-await-in-loop -- sequential by design: one pty at a time
  results.push(await runCase(test));
}

const lines: string[] = [];
lines.push("# Idle mode: live pty evidence (spikes/4-idle-pty.ts)");
lines.push("");
lines.push(
  `generated by: script -q -f -c "tsx spikes/4-idle-app.ts <case>" <capture>`,
);
lines.push("");

for (const result of results) {
  lines.push(
    `RESULT ${result.name} ${result.outcome} rc=${result.rc} rawModeAfter=${String(result.rawModeAfter)} cursorHiddenAfter=${String(result.cursorHiddenAfter)}`,
  );
}

const rawModeLeftOn = results.some((r) => r.rawModeAfter);
const cursorHidden = results.some((r) => r.cursorHiddenAfter);
lines.push(`raw mode left on: ${rawModeLeftOn ? "yes" : "no"}`);
lines.push(`cursor hidden after teardown: ${cursorHidden ? "yes" : "no"}`);
lines.push("");
lines.push("## capture (escapes stripped, first 20 lines each)");
for (const result of results) {
  lines.push(`### ${result.name}`);
  lines.push(
    printable(result.capture)
      .split("\n")
      .filter((line) => line.trim().length > 0)
      .slice(0, 20)
      .join("\n"),
  );
  lines.push("");
}

const submit = results.find((r) => r.name === "submit");
const ctrlc = results.find((r) => r.name === "ctrlc");
const passed =
  submit !== undefined &&
  ctrlc !== undefined &&
  !submit.timedOut &&
  !ctrlc.timedOut &&
  submit.rc === 0 &&
  ctrlc.rc === 0 &&
  submit.outcome.includes('"kind":"input"') &&
  ctrlc.outcome.includes('"kind":"exit"') &&
  ctrlc.outcome.includes('"reason":"command"') &&
  !rawModeLeftOn &&
  !cursorHidden;

lines.push(passed ? "spike passed" : "SPIKE FAILED");
const text = lines.join("\n");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, `${text}\n`, "utf8");
process.stdout.write(`${text}\n`);
process.exitCode = passed ? 0 : 1;
