//! [`CHORD_TABLE`]: the keymap, written out as rows rather than as a match.
//!
//! One row per (mode, liveness, key): what the key does, which component owns
//! it, and what the user is told. The `Ctrl-S` family, `Esc`, the copy chord,
//! `Tab`, Enter — every keystroke the app answers has a row here, and the rule
//! tests in [`tests`](super::tests) read the table instead of the dispatch
//! code: no key has two owners in the same mode and state, every mode has a row
//! for every key that matters, `Ctrl-C` is never a copy, and the table is a
//! table.
//!
//! The shape of a row is [`ChordRow`] in [`chord`](super::chord); the keymap
//! pages in `docs/` are generated out of this array by `scripts/docs_check.py`,
//! which is why a new chord that is not a row here cannot get documented by
//! accident.
use crate::session::view::chord::{ChordRow, ChordState, Effect, KeySym, Owner};

use super::TerminalType;

/// The table. See the comment above it.
pub const CHORD_TABLE: &[ChordRow] = &[
    // ── the control chords, claimed before anything else ──
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::CtrlC,
        keys: "Ctrl-C",
        state: ChordState::Plain,
        owner: Owner::Shell,
        does: Effect::SigInt,
        note: "the shell's own key: 0x03 to the pty master, the foreground group gets SIGINT, \
               the app stays up — and it is never, in any mode, a copy",
    },
    ChordRow {
        mode: TerminalType::Pi,
        key: KeySym::CtrlC,
        keys: "Ctrl-C",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::Quit,
        note: "quit for now: Pi mode has no Cancel worth the name until looprs-5g7, and a copy \
               chord is not what Ctrl-C becomes",
    },
    ChordRow {
        mode: TerminalType::Beads,
        key: KeySym::CtrlC,
        keys: "Ctrl-C",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::Quit,
        note: "same as Pi",
    },
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::CtrlQ,
        keys: "Ctrl-Q",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::Quit,
        note: "quit without touching the shell; this is also why Ctrl-S cannot be forwarded \u{2014} \u{2014} \u{2018} is ours",
    },
    ChordRow {
        mode: TerminalType::Pi,
        key: KeySym::CtrlQ,
        keys: "Ctrl-Q",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::Quit,
        note: "quit in every mode",
    },
    ChordRow {
        mode: TerminalType::Beads,
        key: KeySym::CtrlQ,
        keys: "Ctrl-Q",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::Quit,
        note: "quit in every mode",
    },
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::CtrlS,
        keys: "Ctrl-S",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::ArmChord,
        note: "the copy prefix: a prefix rather than four top-level chords, because the chord budget is the whole difficulty here",
    },
    ChordRow {
        mode: TerminalType::Pi,
        key: KeySym::CtrlS,
        keys: "Ctrl-S",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::ArmChord,
        note: "the copy prefix, armed",
    },
    ChordRow {
        mode: TerminalType::Beads,
        key: KeySym::CtrlS,
        keys: "Ctrl-S",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::ArmChord,
        note: "the copy prefix, armed",
    },
    // ── the chord's second key, armed only ──
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::TargetAnswer,
        keys: "Ctrl-S a",
        state: ChordState::ChordArmed,
        owner: Owner::App,
        does: Effect::CopyAnswer,
        note: "in Bash this *refuses* (there are no answers here) and names the chord that works",
    },
    ChordRow {
        mode: TerminalType::Pi,
        key: KeySym::TargetAnswer,
        keys: "Ctrl-S a",
        state: ChordState::ChordArmed,
        owner: Owner::App,
        does: Effect::CopyAnswer,
        note: "the last answer, whole, through the looprs-pdl.10 sink and toast",
    },
    ChordRow {
        mode: TerminalType::Beads,
        key: KeySym::TargetAnswer,
        keys: "Ctrl-S a",
        state: ChordState::ChordArmed,
        owner: Owner::App,
        does: Effect::CopyAnswer,
        note: "the last answer, whole, through the looprs-pdl.10 sink and toast",
    },
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::TargetOutput,
        keys: "Ctrl-S o",
        state: ChordState::ChordArmed,
        owner: Owner::App,
        does: Effect::CopyLastOutput,
        note: "the last sealed shell block: this command's echo, output and prompt, and nothing before it",
    },
    ChordRow {
        mode: TerminalType::Pi,
        key: KeySym::TargetOutput,
        keys: "Ctrl-S o",
        state: ChordState::ChordArmed,
        owner: Owner::App,
        does: Effect::CopyLastOutput,
        note: "the agentic modes' answer to the same question: the last finished tool card",
    },
    ChordRow {
        mode: TerminalType::Beads,
        key: KeySym::TargetOutput,
        keys: "Ctrl-S o",
        state: ChordState::ChordArmed,
        owner: Owner::App,
        does: Effect::CopyLastOutput,
        note: "the agentic modes' answer to the same question: the last finished tool card",
    },
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::TargetSelection,
        keys: "Ctrl-S s",
        state: ChordState::ChordArmed,
        owner: Owner::App,
        does: Effect::CopySelection,
        note: "whatever selection is live; a keyboard-driven selection was *not* one of the things that landed in this ticket, and this target is ready for it",
    },
    ChordRow {
        mode: TerminalType::Pi,
        key: KeySym::TargetSelection,
        keys: "Ctrl-S s",
        state: ChordState::ChordArmed,
        owner: Owner::App,
        does: Effect::CopySelection,
        note: "whatever selection is live",
    },
    ChordRow {
        mode: TerminalType::Beads,
        key: KeySym::TargetSelection,
        keys: "Ctrl-S s",
        state: ChordState::ChordArmed,
        owner: Owner::App,
        does: Effect::CopySelection,
        note: "whatever selection is live",
    },
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::TargetTranscript,
        keys: "Ctrl-S t",
        state: ChordState::ChordArmed,
        owner: Owner::App,
        does: Effect::DumpTranscriptFile,
        note: "the escape hatch: the whole transcript to a timestamped file, through an injected sink like the clipboard's",
    },
    ChordRow {
        mode: TerminalType::Pi,
        key: KeySym::TargetTranscript,
        keys: "Ctrl-S t",
        state: ChordState::ChordArmed,
        owner: Owner::App,
        does: Effect::DumpTranscriptFile,
        note: "the escape hatch",
    },
    ChordRow {
        mode: TerminalType::Beads,
        key: KeySym::TargetTranscript,
        keys: "Ctrl-S t",
        state: ChordState::ChordArmed,
        owner: Owner::App,
        does: Effect::DumpTranscriptFile,
        note: "the escape hatch",
    },
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::Help,
        keys: "Ctrl-S ?",
        state: ChordState::ChordArmed,
        owner: Owner::App,
        does: Effect::ChordHelp,
        note: "the family, listed in a toast: the chords have to be reachable from inside the app",
    },
    ChordRow {
        mode: TerminalType::Pi,
        key: KeySym::Help,
        keys: "Ctrl-S ?",
        state: ChordState::ChordArmed,
        owner: Owner::App,
        does: Effect::ChordHelp,
        note: "the family, listed in a toast",
    },
    ChordRow {
        mode: TerminalType::Beads,
        key: KeySym::Help,
        keys: "Ctrl-S ?",
        state: ChordState::ChordArmed,
        owner: Owner::App,
        does: Effect::ChordHelp,
        note: "the family, listed in a toast",
    },
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::Esc,
        keys: "Esc",
        state: ChordState::ChordArmed,
        owner: Owner::App,
        does: Effect::CancelChord,
        note: "undoes the prefix and nothing else \u{2014} it is deliberately not the mode's cancel",
    },
    ChordRow {
        mode: TerminalType::Pi,
        key: KeySym::Esc,
        keys: "Esc",
        state: ChordState::ChordArmed,
        owner: Owner::App,
        does: Effect::CancelChord,
        note: "undoes the prefix and nothing else",
    },
    ChordRow {
        mode: TerminalType::Beads,
        key: KeySym::Esc,
        keys: "Esc",
        state: ChordState::ChordArmed,
        owner: Owner::App,
        does: Effect::CancelChord,
        note: "undoes the prefix and nothing else",
    },
    // ── the child holds the screen ──
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::CtrlC,
        keys: "Ctrl-C",
        state: ChordState::ChildHolds,
        owner: Owner::Shell,
        does: Effect::SigInt,
        note: "still SIGINT: a full-screen child does not take Ctrl-C away from the shell it is already in",
    },
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::CtrlQ,
        keys: "Ctrl-Q",
        state: ChordState::ChildHolds,
        owner: Owner::App,
        does: Effect::Quit,
        note: "ours in every state; the child is killed on the way out",
    },
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::CtrlS,
        keys: "Ctrl-S",
        state: ChordState::ChildHolds,
        owner: Owner::App,
        does: Effect::Swallowed,
        note: "never forwarded: XOFF into a pty whose XON (Ctrl-Q) we own is a freeze the user cannot undo",
    },
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::AnyOther,
        keys: "anything else",
        state: ChordState::ChildHolds,
        owner: Owner::Child,
        does: Effect::Forwarded,
        note: "a program that owns the screen owns the keyboard (ADR-0001 Q2) \u{2014} Esc included, so vim leaves insert mode",
    },
    // ── the `Esc` branch, per mode, with the question the ticket asks shown ──
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::Esc,
        keys: "Esc",
        state: ChordState::SelectionLive,
        owner: Owner::App,
        does: Effect::ClearSelection,
        note: "was a selection live? yes \u{2014} the first Esc unselects and sends nothing",
    },
    ChordRow {
        mode: TerminalType::Pi,
        key: KeySym::Esc,
        keys: "Esc",
        state: ChordState::SelectionLive,
        owner: Owner::App,
        does: Effect::ClearSelection,
        note: "was a selection live? yes \u{2014} the first Esc unselects and sends nothing",
    },
    ChordRow {
        mode: TerminalType::Beads,
        key: KeySym::Esc,
        keys: "Esc",
        state: ChordState::SelectionLive,
        owner: Owner::App,
        does: Effect::ClearSelection,
        note: "was a selection live? yes \u{2014} the first Esc unselects and sends nothing",
    },
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::Esc,
        keys: "Esc",
        state: ChordState::Plain,
        owner: Owner::Session,
        does: Effect::CancelRun,
        note: "was a selection live? no \u{2014} the Esc is the cancel the mode table already describes",
    },
    ChordRow {
        mode: TerminalType::Pi,
        key: KeySym::Esc,
        keys: "Esc",
        state: ChordState::Plain,
        owner: Owner::Session,
        does: Effect::CancelRun,
        note: "was a selection live? no \u{2014} the cancel, and the queued text comes back to the box",
    },
    ChordRow {
        mode: TerminalType::Beads,
        key: KeySym::Esc,
        keys: "Esc",
        state: ChordState::Plain,
        owner: Owner::Session,
        does: Effect::CancelRun,
        note: "was a selection live? no \u{2014} the cancel",
    },
    // ── the rest of the table, uniform across modes ──
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::Tab,
        keys: "Tab",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::SwitchMode,
        note: "switch mode; the selection, the chord and the wheel throttle all clear with it",
    },
    ChordRow {
        mode: TerminalType::Pi,
        key: KeySym::Tab,
        keys: "Tab",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::SwitchMode,
        note: "switch mode",
    },
    ChordRow {
        mode: TerminalType::Beads,
        key: KeySym::Tab,
        keys: "Tab",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::SwitchMode,
        note: "switch mode",
    },
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::ShiftTab,
        keys: "Shift-Tab",
        state: ChordState::Plain,
        owner: Owner::Box,
        does: Effect::Newline,
        note: "newline in the input box — Shift-Enter never sends a shell command",
    },
    ChordRow {
        mode: TerminalType::Pi,
        key: KeySym::ShiftTab,
        keys: "Shift-Tab",
        state: ChordState::Plain,
        owner: Owner::Box,
        does: Effect::Newline,
        note: "newline in the input box",
    },
    ChordRow {
        mode: TerminalType::Beads,
        key: KeySym::ShiftTab,
        keys: "Shift-Tab",
        state: ChordState::Plain,
        owner: Owner::Box,
        does: Effect::Newline,
        note: "newline in the input box",
    },
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::ShiftEnter,
        keys: "Shift-Enter",
        state: ChordState::Plain,
        owner: Owner::Box,
        does: Effect::Newline,
        note: "a newline in the box, not a submit",
    },
    ChordRow {
        mode: TerminalType::Pi,
        key: KeySym::ShiftEnter,
        keys: "Shift-Enter",
        state: ChordState::Plain,
        owner: Owner::Box,
        does: Effect::Newline,
        note: "a newline in the box",
    },
    ChordRow {
        mode: TerminalType::Beads,
        key: KeySym::ShiftEnter,
        keys: "Shift-Enter",
        state: ChordState::Plain,
        owner: Owner::Box,
        does: Effect::Newline,
        note: "a newline in the box",
    },
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::Enter,
        keys: "Enter",
        state: ChordState::Plain,
        owner: Owner::Box,
        does: Effect::Submit,
        note: "submit; in Bash this is also where the command boundary is sealed for Ctrl-S o",
    },
    ChordRow {
        mode: TerminalType::Pi,
        key: KeySym::Enter,
        keys: "Enter",
        state: ChordState::Plain,
        owner: Owner::Box,
        does: Effect::Submit,
        note: "submit",
    },
    ChordRow {
        mode: TerminalType::Beads,
        key: KeySym::Enter,
        keys: "Enter",
        state: ChordState::Plain,
        owner: Owner::Box,
        does: Effect::Submit,
        note: "submit",
    },
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::PageUp,
        keys: "PageUp",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::ScrollUp,
        note: "one page up, unpinning the tail (looprs-pdl.8's semantics, the same store)",
    },
    ChordRow {
        mode: TerminalType::Pi,
        key: KeySym::PageUp,
        keys: "PageUp",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::ScrollUp,
        note: "one page up, unpinning the tail",
    },
    ChordRow {
        mode: TerminalType::Beads,
        key: KeySym::PageUp,
        keys: "PageUp",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::ScrollUp,
        note: "one page up, unpinning the tail",
    },
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::PageDown,
        keys: "PageDown",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::ScrollDown,
        note: "one page down; reaching the bottom re-pins",
    },
    ChordRow {
        mode: TerminalType::Pi,
        key: KeySym::PageDown,
        keys: "PageDown",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::ScrollDown,
        note: "one page down; reaching the bottom re-pins",
    },
    ChordRow {
        mode: TerminalType::Beads,
        key: KeySym::PageDown,
        keys: "PageDown",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::ScrollDown,
        note: "one page down; reaching the bottom re-pins",
    },
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::Home,
        keys: "Home",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::Top,
        note: "top of the transcript",
    },
    ChordRow {
        mode: TerminalType::Pi,
        key: KeySym::Home,
        keys: "Home",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::Top,
        note: "top of the transcript",
    },
    ChordRow {
        mode: TerminalType::Beads,
        key: KeySym::Home,
        keys: "Home",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::Top,
        note: "top of the transcript",
    },
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::End,
        keys: "End",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::Tail,
        note: "bottom, and re-pin: what the \u{201c}N new\u{201d} affordance names",
    },
    ChordRow {
        mode: TerminalType::Pi,
        key: KeySym::End,
        keys: "End",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::Tail,
        note: "bottom, and re-pin",
    },
    ChordRow {
        mode: TerminalType::Beads,
        key: KeySym::End,
        keys: "End",
        state: ChordState::Plain,
        owner: Owner::App,
        does: Effect::Tail,
        note: "bottom, and re-pin",
    },
    ChordRow {
        mode: TerminalType::Bash,
        key: KeySym::AnyOther,
        keys: "anything else",
        state: ChordState::Plain,
        owner: Owner::Box,
        does: Effect::Typing,
        note: "typing, to whichever mode's box is up",
    },
    ChordRow {
        mode: TerminalType::Pi,
        key: KeySym::AnyOther,
        keys: "anything else",
        state: ChordState::Plain,
        owner: Owner::Box,
        does: Effect::Typing,
        note: "typing",
    },
    ChordRow {
        mode: TerminalType::Beads,
        key: KeySym::AnyOther,
        keys: "anything else",
        state: ChordState::Plain,
        owner: Owner::Box,
        does: Effect::Typing,
        note: "typing",
    },
];
